config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  namespace :admin do
    resources :orders, only: [:index]
    resources :products
  end

  resources :products
  resources :line_items
  resources :carts, path: :mon_panier do
    resources :charges, only: [:create, :new], path: :paiement
  end
  resources :users, path: :mon_profil

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :products, through: :line_items

  def add_product(product) 
    item = line_items.find_by(product_id: product)

    if item 
        item.quantity += 1 
    else
         item = line_items.new(product: product)
    end
    return item
  end

  def total
    line_items.to_a.sum(&:total)
  end 
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    total = quantity * product.price
  end 
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  after_create :order_send

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.info_new_order(self).deliver_now
  end

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    has_many :line_items
    has_many :carts, through: :line_items
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #:confirmable
  
  has_one_attached :avatar
  has_many :carts       
  
  validates_presence_of :first_name, :last_name

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :is_admin, only: [:index]
    def index
        @orders = Order.all
    end

    private

    def is_admin
       unless current_user.is_admin == true
        redirect_to '/'
       end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :is_admin

    def index
        @products = Product.all
        @line_item = LineItem.all
    end

    def show
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.create(product_params)
        if @product.save
            redirect_to admin_products_path, :flash => { :success => "Vous avez creer votre produit avec succès" }
        else
            redirect_to new_admin_product
        end
    end

    def edit
    end

    def update
     
        @product = Product.update(product_params)
        if @product.update
            redirect_to admin_orders_path
        end
    end

    def destroy
        @product.destroy
        redirect_to admin_products_path
    end

    private

    def is_admin
        unless current_user.is_admin == true
            redirect_to '/'
        end
    end

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :info, :error, :warning, :success, :notice, :danger

  before_action :configure_devise_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session

    def configure_devise_parameters
			devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :avatar, :password_confirmation)}
			devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email,:avatar, :password, :password_confirmation, :current_password)}
			
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    before_action :check_user, only: [:show]

    def index 
        @carts = Cart.all
    end

    def create
        @cart = Cart.create(user: current_user)
        redirect_to '/products'
    end

    def show
        @cart = Cart.find(params[:id])
    end

    def destroy
        @cart = Cart.find(params[:id])
        @items = LineItem.where(cart: @cart)
        @items.each do |item|
            item.destroy
        end
        @cart.destroy
        redirect_to '/products'
    end

    private 

    def check_user
        @cart = Cart.find(params[:id])
        redirect_to '/products' unless current_user == @cart.user
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    before_action :authenticate_user!, only: [:create, :new]
    before_action :check_user, only: [:create, :new]

    def new
        @cart = Cart.find(params[:cart_id])
    end
    
    def create
      # Amount in cents
      @cart = Cart.find(params[:cart_id])
      @amount = 500

      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
      })
    
    @order = Order.create(stripe_customer_id: customer.id, user_id: current_user.id) 
   
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    private 

    def check_user
        @cart = Cart.find(params[:cart_id])
        redirect_to '/products' unless current_user == @cart.user
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
    def set_cart
        if user_signed_in?
            @cart = Cart.find_or_create_by(user_id: current_user.id)
            @cart = Cart.last
        end            
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
    include CurrentCart
    before_action :set_cart, only: [:create]
    before_action :authenticate_user!, only: [:new,:create, :destroy]

    def new
        @line_item = LineItem.new
    end

    def create
        product = Product.find(params[:product_id])
        @line_item = @cart.add_product(product)
        
        if @line_item.save 
            redirect_to '/', success: "vous avez ajouté #{product.title} avec succès"
        else
            redirect_to '/'
        end
    end

    def destroy
        @line_item = LineItem.find(params[:id])
        @line_item.destroy
        redirect_to @line_item.cart, info: "Vous avez supprimer votre produit avec succès"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :product_params, only: [:edit, :update]
    before_action :is_admin, only: [:update]
    def index
        @products = Product.all
    end

    def show 
        @product = Product.find(params[:id])
        @products = Product.all
        i = 1 
        @products.each do |img|
          if img == @product
           @img = "chaton#{i}.jpg"
          end
          i += 1
        end
    end
    def edit
    end

    def update
        @product = Product.update(product_params)
        redirect_to admin_orders_path
    end
    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
    end

    private 
    def is_admin
        unless current_user.is_admin == true
            redirect_to '/'
        end
    end

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_user?, only: [:show]
  

    def show 
      @user = User.find(params[:id])
      @order = Order.where(user: current_user)
    end

  
      private
  
    def is_user?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:alert] = "action impossible !"
        redirect_to "/"
      end
    end


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/orders/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navbar">
  <a class="navbar-brand text-white" href="/"><span class="text-secondary">E</span>-chaton</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarColor03">
    <ul class="navbar-nav navbar-center">
      
    </ul>


    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Dashboard Accueil', admin_orders_path%></a>
    </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Gerer les Produits</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" href="<%=admin_products_path%>">Vos produits</a>
          <a class="dropdown-item menu-nav text-white" href="<%=new_admin_product_path%>">Nouveau produit</a>
        <a class="dropdown-item menu-nav text-white" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
        </div>
    </ul> 
  </div>
</nav>

app/views/admin/orders/index.html.erb
<%= render "sidebar"%>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 mb-4">

                       
                            <div class="container-fluid">
																<div class="container m-5">
																	<div class="row">
																		<div class="col-12">
																				<div class="table-responsive">
																						<table class="table table-striped">
																								<thead>
																										<tr>
																											<th scope="col"> </th>
																											<th scope="col"> Utilisateurs</th>
																											<th scope="col">Produits</th>
																											<th scope="col" class="text-center">Quantité</th>
																											<th scope="col" class="text-center">Prix</th>
																										</tr>
																								</thead>
																								<tbody>
																								<% @orders.each do |order|%> 
																												
																													
																											
																												<% order.user.carts[0].line_items.each do |p| %>
																													<tr>
																														<td></td>
																														<td><%= order.user.first_name%></td>
																														<td><%= p.product.title%></td>
																														<td class="text-center"><%= p.quantity%> </td>
																														<td class='text-center'><%= p.total%>€</td>
																													</tr>
																												<% end %>
																										
																								<% end %>
																										
																								</tbody>
																						</table>
																				</div>
																		</div>
																	</div>
																</div>
															</div>

                        </div>

                        
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            
        </div>
        
    </div>
   

app/views/admin/products/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navbar">
  <a class="navbar-brand text-white" href="/"><span class="text-secondary">E</span>-chaton</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarColor03">
    <ul class="navbar-nav navbar-center">
      
    </ul>


    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
                <a class="nav-link" <%= link_to 'Dashboard Accueil', admin_orders_path%></a>
            </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Gerer les Produits</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" href="<%=admin_products_path%>">Vos produits</a>
          <a class="dropdown-item menu-nav text-white" href="<%=new_admin_product_path%>">Nouveau produit</a>
          <a class="dropdown-item menu-nav text-white" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
        </div>
    </ul> 
  </div>
</nav>

app/views/admin/products/edit.html.erb
<%= render 'shared/ban'%>
<%= render 'sidebar' %>
<div class="container mb-5">

  <%= simple_form_for @product do |f| %>
  <h2 class="p-5">Editer le produit</h2>

    <div class="form-inputs">
      <%= f.input :title,
                  autofocus: true,
                  input_html: { autocomplete: "Nom du produit" }%>
      <%= f.input :description,
                  input_html: { autocomplete: "Description" }%>
      <%= f.input :price,
                  input_html: { autocomplete: "Prix" }%>
      <%= f.input :image, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Créer",:class => 'btn btn-primary' %>
    </div>

  <% end %>

</div>

app/views/admin/products/index.html.erb
<%= render 'sidebar' %>

  <section>
  
    <div id="product-all" class="text-center pt-5">
      <h1 class="p-5" style="font-size: 60px;">Nos photos</h1>
      <div id="product-align">
      <% i = 1 %>
      <% @products.each do |product| %>
      <div class="card mb-5" id="card-product">
        <%= image_tag ("chaton#{i}.jpg"), alt: 'cat-image', class: "card-img-top card-img"%>
        <div class="card-body">
          <h5 class="card-title">Nom: <%= product.title%></h5>
          <p class="text-primary"> <%= product.description %></p>
          <h4 class="card-text text-danger"><%= product.price %> €</h4>
          <div class="bot-button">
          <%= link_to "Voir le produit", admin_product_path(product), class: "btn btn-primary mt-3" %>
          <%= link_to "supprimer", admin_product_path(product), method: 'DELETE', class: "btn btn-danger mt-3" %>
          </div>
        </div>
      </div>
      <% i += 1 %>
      <% end %>
      
    </div>
      
    </div>
    
  </section>

app/views/admin/products/new.html.erb
<%= render 'shared/ban'%>
<%= render 'sidebar' %>
<div class="container mb-5">

  <%= simple_form_for @product, :url => admin_products_path do |f| %>
  <h2 class="p-5">Nouveau Produit</h2>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  autofocus: true,
                  input_html: { autocomplete: "Nom du produit" }%>
      <%= f.input :description,
                  input_html: { autocomplete: "Description" }%>
      <%= f.input :price,
                  input_html: { autocomplete: "Prix" }%>
      <%= f.input :image, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Créer",:class => 'btn btn-primary' %>
    </div>

  <% end %>

</div>

app/views/admin/products/show.html.erb
<%= render 'sidebar'%>
    
    <!-- Tout dans un container -->
    <div class='container mw-100'>
      
        <!-- Molécule image (8 colonnes) + informations (4 colonnes)-->
        <div class='header mw-100' style='background-image: url(https://www.leparisien.fr/resizer/74wMQIeXKLDUKuKvSzJQME_0ULg=/932x582/arc-anglerfish-eu-central-1-prod-leparisien.s3.amazonaws.com/public/KNVYKZBDTTOXNO37FEVDTD5DJU.jpg);'>
          <div class='row px-5'>
            <div class='col-7 p-5'>
              <img src='https://www.leparisien.fr/resizer/74wMQIeXKLDUKuKvSzJQME_0ULg=/932x582/arc-anglerfish-eu-central-1-prod-leparisien.s3.amazonaws.com/public/KNVYKZBDTTOXNO37FEVDTD5DJU.jpg' style='max-width: 100%;max-height:100%;display:block;'>
            </div>
            
          </div>
        </div>
        
        <!-- Molécule avec des icones, puis un bouton -->
        <div class='header mw-100' style='background-color: lightgoldenrodyellow;'>
          <div class='row'>
            <div class='col'></div>
          </div>
        </div>
        
        
        <!-- Molécule Description (8 colonnes) + informations (4 colonnes) -->
        <div class='row px-5'>
          <div class='col-8 pt-5 px-5'>
            <h1>Nom du Produit:</h1>
            <h3><%= @product.title %></h3>
            <h1> Description: </h1>
            <h3><%= @product.description %></h3>
            <a class="nav-link btn btn-primary" <%= link_to 'Editer le produit', edit_admin_product_path(@product)%></a>
            <br>
          </div>
          </div>
        </div>

        

        <!-- Molécule autres produits-->

  </div>

app/views/carts/index.html.erb
hihihihihi

app/views/carts/show.html.erb
<%= render 'layouts/navbar'%>
<%= render 'shared/ban'%>
<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Produit</th>
                            <th scope="col">Disponible</th>
                            <th scope="col" class="text-center">Quantité</th>
                            <th scope="col" class="text-right" style="width: 100px;">Prix</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                    <% @cart.line_items.each do |p| %>
                        <tr>
                            <td><%= image_tag p.product.image, alt: 'cat-image', class: "card-img-top card-img"  %> </td>
                            <td><%= p.product.title%></td>
                            <td>En stock</td>
                            <td><input class="form-control" type="text" value="<%= p.quantity%>" /></td>
                            <td class="text-right"><%= p.total%> €</td>
                            <td class="text-right">
                                <%= link_to ('<i class="fa fa-trash"></i>').html_safe, line_item_path(p), method: 'DELETE'%> 
                            </td>
                        </tr>
                    <% end %>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong><%= @cart.total%> </strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <%= link_to 'Continuer le shopping', products_path, class: 'btn btn-block btn-light'%>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <%= link_to 'Confirmer la commande', new_cart_charge_path(@cart), class: "btn btn-lg btn-block btn-success "%>
                </div>
            </div>
        </div>
    </div>
</div>
</main>


  <%= render 'layouts/footer'%>

app/views/charges/create.html.erb
<header>
  <%= render 'layouts/navbar2'%>
</header>
<div class="container mb-4 p-5 text-center">
<h2>Merci Pour vos achats!</h2>
  <h3>Récapitulatif de votre commande</h3>
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Produit</th>
                            <th scope="col">Prix</th>
                            
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                    <% @cart.line_items.each do |p| %>
                        <tr>
                            <td><%= image_tag p.product.image, alt: 'cat-image', class: "card-img-top card-img"  %> </td>
                            <td><%= p.product.title%></td>
                            
                            
                            <td class="text-right"><%= p.total%>€</td>
                            
                        </tr>
                    <% end %>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <h4> Vous avez payé <strong> <%= @cart.total %> €</strong></h4>
            </div>
        </div>
    </div>
</div>
<%= link_to "Retour à la page d'acceuil", carts_path, method: :post, class: 'btn btn-outline-danger w-25 mx-auto mb-5'%>

</main>


<%= render 'layouts/footer'%>

app/views/charges/new.html.erb
<%= render 'layouts/navbar2' %>
<%= render 'shared/ban' %>


<%# ------- module de paiement --------- %>

<main class="d-flex justify-content-center">
  <div> 
    <div class="container px-5 m-5">
        <div class="row">
          <div class="col-6-md">
            <h4> Récapitulatif de la commande </h4>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            <th scope="col" class="text-center">Quantity</th>
                            <th scope="col" class="text-right">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                    <% @cart.line_items.each do |p| %>
                        <tr>
                            <td><%= p.product.title%></td>
                            <td>In stock</td>
                            <td><%= p.quantity%></td>
                            <td><%= p.total%> €</td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
          </div>

          <div class="col-6" style="display:flex; align-items: center; justify-content: center">
              <%= form_tag cart_charges_path do %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  <label class="amount">
                    <span><h4>Montant total : <%= @cart.total %>€</h4></span>
                  </label>
                </article>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="Tu va te faire banane"
                        data-amount= "<%= sprintf("%.2f",(@cart.total)).delete '.'.to_s %>"
                        data-currency="eur"
                        data-locale="auto"
                        data-label="PAYER">
                        </script>
              <% end %>
          </div>
        </div>
      </div>

    <%# ------- paiement securisé --------- %>


      <div class="container px-5 m-5">
        <div class="row">
            <div class="col">
              <img src="https://www.argent-tres-facile.com/wp-content/uploads/2018/12/paiement-securise-garantie.png">
            <div>
          </div>
        </div>
      </div>


      </div>
    </div>

  </main>

<%= render 'layouts/footer' %>

app/views/products/_jumbotron.html.erb
<div class="container-fluid" id="test">
  <%= render 'layouts/navbar'%>

  <% flash.each do |name, msg|%>
    <div class='pos-alert text-center alert alert-<%= name %>'>
      <%= msg %>
    </div>
  <% end %>
  <%= image_tag 'jumbotron-chat2.png', class: "stick"%>
  <%= image_tag 'jumbotron-first.png', id: "image-fond1"%>
</div>
      

app/views/products/index.html.erb
<%= render "jumbotron" %>

  <section>
  
    <div id="product-all" class="text-center pt-5">
      <h1 class="p-5" style="font-size: 60px;">Nos photos</h1>
      <div id="product-align">
      <% i = 1 %>
      <% @products.each do |product| %>
      <div class="card mb-5" id="card-product">
        <%= image_tag ("chaton#{i}.jpg"), alt: 'cat-image', class: "card-img-top card-img"%>
        <div class="card-body">
          <h5 class="card-title">Nom: <%= product.title%></h5>
          <p class="text-primary"> <%= product.description %></p>
          <h4 class="card-text text-danger"><%= product.price %> €</h4>
          <div class="bot-button">
          <%= link_to "Ajouter au panier", line_items_path(product_id: product.id), method: 'POST', class: "btn btn-secondary" %>
          <%= link_to "Voir le produit", product_path(product), class: "btn btn-primary mt-3" %>
          </div>
        </div>
      </div>
      <% i += 1 %>
      <% end %>
    </div>
      
    </div>
    
  </section>
  <footer>
  <%= render 'layouts/footer'%>
  </footer>

app/views/products/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>
  <body>
  <%= render 'layouts/navbar2'%>
    
    <!-- Tout dans un container -->
    <div class='container mw-100'>
      
        <!-- Molécule image (8 colonnes) + informations (4 colonnes)-->
        <div class='header mw-100' id="background" style='background-image: url(https://www.leparisien.fr/resizer/74wMQIeXKLDUKuKvSzJQME_0ULg=/932x582/arc-anglerfish-eu-central-1-prod-leparisien.s3.amazonaws.com/public/KNVYKZBDTTOXNO37FEVDTD5DJU.jpg);'>
          <div class='row px-5'>
            <div class='col-7 p-5'>
              <%= image_tag (@img), alt: 'cat-image', style: 'width: 700px; display:block;'%>
            </div>
            <div class='tic col-4 p-5 m-4 rounded' style='background-color:white; border: 1px solid #b9bbc9'>
              <h1> <%= @product.title %> </h1>
              <h2> <%= @product.price %>€ </h2>
              <br></br>
              <a class="btn btn-primary " <%= link_to "Ajouter au panier", line_items_path(product_id: @product.id), method: 'POST' %></a>	

            </div>
          </div>
        </div>
        
        <!-- Molécule avec des icones, puis un bouton -->
        <div class='header mw-100' style='background-color: lightgoldenrodyellow;'>
          <div class='row'>
            <div class='col p-3'>
              <a class="ins-ic ml-3 mr-3" role="button"><i class="fab fa-lg fa-instagram"></i></a>
              <!--Pinterest-->
              <a class="pin-ic mr-3" role="button"><i class="fab fa-lg fa-pinterest"></i></a>
              <!--WhatsApp-->
              <a class="whatsapp-ic" role="button"><i class="fab fa-lg fa-whatsapp"></i></a>
            </div>
            <div class='col'></div>
          </div>
        </div>
        
        
        <!-- Molécule Description (8 colonnes) + informations (4 colonnes) -->
        <div class='row px-5'>
          <div class='col-8 pt-5 px-5'>
           <h3> Description </h3>
            <p><%= @product.description %></p>
            <br>
           <h3> A propos de la livraison </h3>
            <p>Chaque création est imprimée avec soin et contrôlée à la main dans nos ateliers, puis livrée à temps quelle que soit l’occasion.

            <p><b>Vous commandez en grandes quantités ? </b> </p> 
            <p>Consultez nos remises sur les ventes en gros.</p>
          </div>
          </div>
        </div>

        <!-- Molécule icones de réseaux sociaux-->
        
          <div class='row px-5 pb-5'>
            <div class='col-8 pt-5 px-5'>
              <h5>Partager-la avec vos Amis</h5>
              <!--Facebook-->
              <a class="fb-ic mr-3" role="button"><i class="fab fa-lg fa-facebook-f"></i></a>
              <!--Twitter-->
              <a class="tw-ic mr-3" role="button"><i class="fab fa-lg fa-twitter"></i></a>
              <!--Google +-->
              <a class="gplus-ic mr-3" role="button"><i class="fab fa-lg fa-google-plus-g"></i></a>
              <!--Instagram-->
              <a class="ins-ic mr-3" role="button"><i class="fab fa-lg fa-instagram"></i></a>
              <!--Pinterest-->
              <a class="pin-ic mr-3" role="button"><i class="fab fa-lg fa-pinterest"></i></a>
              <!--WhatsApp-->
              <a class="whatsapp-ic" role="button"><i class="fab fa-lg fa-whatsapp"></i></a>
            </div>
            <div class='col-4'></div>
          </div>
      </div>

        <!-- Molécule autres produits-->

  </div>
</body>


<%= render 'layouts/footer'%>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>