config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  namespace :admin do
    resources :orders, only: [:index]
    resources :products
  end

  resources :products
  resources :line_items
  resources :carts, path: :mon_panier do
    resources :charges, only: [:create, :new], path: :paiement
  end
  resources :users, path: :mon_profil

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :products, through: :line_items

  def add_product(product) 
    item = line_items.find_by(product_id: product)

    if item 
        item.quantity += 1 
    else
         item = line_items.new(product: product)
    end
    return item
  end

  def total
    line_items.to_a.sum(&:total)
  end 
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    total = quantity * product.price
  end 
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  after_create :order_send

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.info_new_order(self).deliver_now
  end

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    has_many :line_items
    has_many :carts, through: :line_items
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #:confirmable
  
  has_one_attached :avatar
  has_many :carts       
  
  validates_presence_of :first_name, :last_name

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :is_admin, only: [:index]
    def index
        @orders = Order.all
    end

    private

    def is_admin
       unless current_user.is_admin == true
        redirect_to '/'
       end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :info, :error, :warning, :success, :notice, :danger

  before_action :configure_devise_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session

    def configure_devise_parameters
			devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :avatar, :password_confirmation)}
			devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email,:avatar, :password, :password_confirmation, :current_password)}
			
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    before_action :check_user, only: [:show]

    def index 
        @carts = Cart.all
    end

    def create
        @cart = Cart.create(user: current_user)
        redirect_to '/products'
    end

    def show
        @cart = Cart.find(params[:id])
    end

    def destroy
        @cart = Cart.find(params[:id])
        @items = LineItem.where(cart: @cart)
        @items.each do |item|
            item.destroy
        end
        @cart.destroy
        redirect_to '/products'
    end

    private 

    def check_user
        @cart = Cart.find(params[:id])
        redirect_to '/products' unless current_user == @cart.user
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    before_action :authenticate_user!, only: [:create, :new]
    before_action :check_user, only: [:create, :new]

    def new
        @cart = Cart.find(params[:cart_id])
    end
    
    def create
      # Amount in cents
      @cart = Cart.find(params[:cart_id])
      @amount = 500

      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
      })
    
    @order = Order.create(stripe_customer_id: customer.id, user_id: current_user.id) 
   
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    private 

    def check_user
        @cart = Cart.find(params[:cart_id])
        redirect_to '/products' unless current_user == @cart.user
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
    def set_cart
        if user_signed_in?
            @cart = Cart.find_or_create_by(user_id: current_user.id)
            @cart = Cart.last
        end            
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
    include CurrentCart
    before_action :set_cart, only: [:create]
    before_action :authenticate_user!, only: [:new,:create, :destroy]

    def new
        @line_item = LineItem.new
    end

    def create
        product = Product.find(params[:product_id])
        @line_item = @cart.add_product(product)
        
        if @line_item.save 
            redirect_to '/', success: "vous avez ajouté #{product.title} avec succès"
        else
            redirect_to '/'
        end
    end

    def destroy
        @line_item = LineItem.find(params[:id])
        @line_item.destroy
        redirect_to @line_item.cart, info: "Vous avez supprimer votre produit avec succès"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :product_params, only: [:edit, :update]
    before_action :is_admin, only: [:update]
    def index
        @products = Product.all
    end

    def show 
        @product = Product.find(params[:id])
        @products = Product.all
        i = 1 
        @products.each do |img|
          if img == @product
           @img = "chaton#{i}.jpg"
          end
          i += 1
        end
    end
    def edit
    end

    def update
        @product = Product.update(product_params)
        redirect_to admin_orders_path
    end
    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
    end

    private 
    def is_admin
        unless current_user.is_admin == true
            redirect_to '/'
        end
    end

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_user?, only: [:show]
  

    def show 
      @user = User.find(params[:id])
      @order = Order.where(user: current_user)
    end

  
      private
  
    def is_user?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:alert] = "action impossible !"
        redirect_to "/"
      end
    end


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
        <footer class="page-footer font-small mdb-color lighten-3 pt-4">

            <!-- Footer Links -->
            <div class="container text-center text-md-left">
        
            <!-- Grid row -->
            <div class="row">
        
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
        
                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Notre site :</h5>
                <p>Bienvenue sur notre site, <br /> où vous pourrez acheter <br /> les plus belles images de chaton !</p>
        
                </div>
                <!-- Grid column -->
        
                <hr class="clearfix w-100 d-md-none">
        
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">
        
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mb-4">A propos</h5>
        
                <ul class="list-unstyled">
                    <li>
                    <p>
                        <a href="#!">PROJETS</a>
                    </p>
                    </li>
                    <li>
                    <p>
                        <a href="#!">NOTRE EQUIPE</a>
                    </p>
                    </li>
                    <li>
                    <p>
                        <a href="#!">BLOG</a>
                    </p>
                    </li>
                    <li>
                    <p>
                        <a href="#!">AWARDS</a>
                    </p>
                    </li>
                </ul>
        
                </div>
                <!-- Grid column -->
        
                <hr class="clearfix w-100 d-md-none">
        
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
        
                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">Contact</h5>
        
                <ul class="list-unstyled">
                    <li>
                    <p>
                        <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
                    </li>
                    <li>
                    <p>
                        <i class="fas fa-envelope mr-3"></i> info@example.com</p>
                    </li>
                    <li>
                    <p>
                        <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
                    </li>
                    <li>
                    <p>
                        <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
                    </li>
                </ul>
        
                </div>
                <!-- Grid column -->
        
                <hr class="clearfix w-100 d-md-none">
        
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
        
                <!-- Social buttons -->
                <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>

                <ul class="list-unstyled">
                    <li>
                    <p>
                      <a type="button" class="btn-floating btn-fb m-2">
                        <i class="fab fa-facebook-f"></i>
                      </a>
                    </li>
                    <li>
                    <p>
                      <a type="button" class="btn-floating btn-tw m-2">
                        <i class="fab fa-twitter"></i>
                      </a>
                    </li>
                    <li>
                    <p>
                      <a type="button" class="btn-floating btn-gplus m-2">
                        <i class="fab fa-google-plus-g"></i>
                      </a>
                    </li>
                    
                </ul>
                
                </div>
        
          
            </div>

            <div class="footer-copyright text-center py-3">© 2020 Copyright :
            <a href="#">Girondins de Paris</a>
            </div>
        
        </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navbar">
  <a class="navbar-brand text-white" href="/"><span class="text-secondary">E</span>-chaton</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarColor03">
    <ul class="navbar-nav navbar-center">
      

    </ul>


    <ul class="navbar-nav ml-auto">
    <% if current_user && current_user.is_admin == true%>
    <li class="nav-item active">
      <a class="nav-link" <%= link_to 'Dashboard Admin', admin_orders_path%></a>
    </li>
    <% end %>
    <% if user_signed_in?%>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profil/Quitter</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
          <a class="dropdown-item menu-nav text-white" <%= link_to "Profil", user_path(current_user) %></a>
        </div>
      </li>
      <% if current_user.carts[0] %>
        <li class="mx-3 pt-2 text-secondary"><%= link_to ('<i class="fas fa-shopping-cart fa-lg"></i>').html_safe, cart_path(current_user.carts.last) ,class:"text-secondary" %></li>
      <% end %>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Se Connecter/S'inscrire</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" href="<%=new_user_session_path%>">Se connecter</a>
          <a class="dropdown-item menu-nav text-white" href="<%=new_user_registration_path%>">S'inscrire</a>
        </div>
    </ul> 
    <% end %>
  </div>
</nav>

app/views/layouts/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navbar">
  <a class="navbar-brand text-white" href="/"><span class="text-secondary">E</span>-chaton</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarColor03">
    <ul class="navbar-nav navbar-center">
      
    </ul>


    <ul class="navbar-nav ml-auto">
    <% if user_signed_in?%>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profil/Quitter</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
          <a class="dropdown-item menu-nav text-white" <%= link_to "Profil", user_path(current_user) %></a>
        </div>
      </li>
      <% if current_user.carts[0] %>
        <li class="mx-3 pt-2 text-secondary"><%= link_to ('<i class="fas fa-shopping-cart fa-lg"></i>').html_safe, cart_path(current_user.carts.last) ,class:"text-secondary" %></li>
      <% end %>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Se Connecter/S'inscrire</a>
        <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item menu-nav text-white" href="<%=new_user_session_path%>">Se connecter</a>
          <a class="dropdown-item menu-nav text-white" href="<%=new_user_registration_path%>">S'inscrire</a>
        </div>
    </ul> 
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoutiqueEChaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/shared/_ban.html.erb
      <div class="sm-ban align-items-center">
            <div class="container ">
              <h2 class="title-ban">Vive les chatons</h2>
            </div>
          </div>

app/views/shared/_chatonban.html.erb
<div class="sm-ban-pay align-items-center mb-5">
            <div class="container ">
              <h3>Merci pour votre commande</h3>
            </div>
          </div>